version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: 
      - sh 
      - -c
      - |
        EDITOR=echo rails credentials:edit
        chmod u+x bin/rails
        rm -f tmp/pids/server.pid
        rails assets:precompile
        rails s -p 3000
    volumes:
      - .:/Rails-Docker
    environment:
      RAILS_ENV: production
      RAILS_RELATIVE_URL_ROOT: /rails
      RAILS_SERVE_STATIC_FILES: true
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres:
